commit

diff --git a/.github/workflows/buildAndDeploy.yaml b/.github/workflows/buildAndDeploy.yaml
--- a/.github/workflows/buildAndDeploy.yaml
+++ b/.github/workflows/buildAndDeploy.yaml
@@ -49,14 +49,14 @@ jobs:
             key: ${{ secrets.AWS_KEY }}        # SSH private key from secrets
             port: 22                           # SSH port (default 22)
             script: |
-                  # Check if Docker is installed
-                  if ! command -v docker &> /dev/null; then
-                    echo "Docker not found. Installing Docker..."
-                    curl -fsSL https://get.docker.com -o get-docker.sh
-                    sudo sh get-docker.sh
-                  else
-                    echo "Docker is already installed."
-                  fi
+              # Check if Docker is installed
+              if ! command -v docker &> /dev/null; then
+              echo "Docker not found. Installing Docker..."
+              curl -fsSL https://get.docker.com -o get-docker.sh
+              sudo sh get-docker.sh
+              else
+                echo "Docker is already installed."
+              fi
               echo "Pulling latest Docker image from Docker Hub..."
               sudo docker pull victormsonter/cloud_drill:latest
               
